blueprint:
  name: MintBlueJelly - Activate Scenes on Motion v1.0.1
  description: "Use motion sensors to activate different scenes during day and night."
  domain: automation
  input:
    triggers:
      name: Triggers
      description: "Select one or more motion sensors to trigger the automation."
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: motion
    day_scene:
      name: Day Scene
      description: "Select the scene to be activated when the sun is above the horizon."
      selector:
        entity:
          domain: scene
    day_offset:
      name: Day Offset
      description: "Specify the seconds to shift the start of the day back or forth."
      default: 0
      selector:
        number:
          min: -3600
          max: 3600
          unit_of_measurement: seconds
    night_scene:
      name: Night Scene
      description: "Select the scene to be activated when the sun is below the horizon."
      selector:
        entity:
          domain: scene
    night_offset:
      name: Night Offset
      description: "Specify the seconds to shift the start of the night back or forth."
      default: 0
      selector:
        number:
          min: -3600
          max: 3600
          unit_of_measurement: seconds
    off_scene:
      name: Off Scene
      description: "Select the scene to be activated when motion is no longer detected."
      selector:
        entity:
          domain: scene
    timeout:
      name: Timeout
      description: "Specify the delay before the off scene is activated."
      default: 10
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
    cross_fade:
      name: Cross-Fade
      description: "Specify the time to cross-fade from one scene to the next."
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          unit_of_measurement: seconds
  source_url: "https://raw.githubusercontent.com/MintBlueJelly/ha-blueprints/main/Activate%20Scenes%20on%20Motion/cys-v1.yaml"

trigger:
  # Trigger when motion is detected
  - platform: state
    entity_id: !input triggers
    to: "on"

action:
  # Choose action based on the sun's elevation
  - choose:
      # Sun is below the horizon
      - conditions:
          - condition: sun
            after: sunset
            after_offset: !input night_offset
            before: sunrise
            before_offset: !input day_offset
        sequence:
          # Activate night scene
          - service: scene.turn_on
            data:
              transition: !input cross_fade
            target:
              entity_id: !input night_scene
      # Sun is above the horizon
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: !input day_offset
            before: sunset
            before_offset: !input night_offset
        sequence:
          # Activate day scene
          - service: scene.turn_on
            data:
              transition: !input cross_fade
            target:
              entity_id: !input day_scene
  # Await timeout once motion is no longer detected
  - wait_for_trigger:
      - platform: state
        entity_id: !input triggers
        to: "off"
        for:
          seconds: !input timeout
  # Activate off scene
  - service: scene.turn_on
    data:
      transition: !input cross_fade
    target:
      entity_id: !input off_scene

# Restart automation when trigger fires again
mode: restart
