blueprint:
  name: MintBlueJelly - Activate Scenes on Motion v1.0.2
  description: |
    ## Description
    This blueprint uses motion sensors to activate different scenes during day or night.

    ## Updates
    - This blueprint is designed to be updatable within major versions (e.g. `v1.x.x`).
    - If a breaking change is unavoidable, it will trigger a new major version (e.g. `2.0.0`).
    - Each major version will be published as a new blueprint in my GitHub repository (e.g. `xxx-v2.yaml`).
    - Minor version updates will be patched into the existing blueprint. They can be safely pulled into your Home Assistant instance by re-importing the blueprint via its context menu.

    See my GitHub repository for more blueprints:
    https://github.com/MintBlueJelly/ha-blueprints
  domain: automation
  input:
    triggers:
      name: Triggers
      description: "One or more motion sensors to trigger the automation"
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: motion
    day_scene:
      name: Day Scene
      description: "Will be activated when the sun is above the horizon"
      selector:
        entity:
          domain: scene
    day_offset:
      name: Day Offset
      description: "Shifts the start of the day back or forth"
      default: 0
      selector:
        number:
          min: -3600
          max: 3600
          unit_of_measurement: seconds
    night_scene:
      name: Night Scene
      description: "Will be activated when the sun is below the horizon"
      selector:
        entity:
          domain: scene
    night_offset:
      name: Night Offset
      description: "Shifts the start of the night back or forth"
      default: 0
      selector:
        number:
          min: -3600
          max: 3600
          unit_of_measurement: seconds
    off_scene:
      name: Off Scene
      description: "Will be activated when motion is no longer detected"
      selector:
        entity:
          domain: scene
    timeout:
      name: Timeout
      description: "Delays off scene after motion is no longer detected"
      default: 10
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
    cross_fade:
      name: Cross-Fade
      description: "Cross-fade duration when scenes change"
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 10
          unit_of_measurement: seconds
  source_url: "https://raw.githubusercontent.com/MintBlueJelly/ha-blueprints/main/Activate%20Scenes%20on%20Motion/cys-v1.yaml"

trigger:
  # Trigger when motion is detected
  - platform: state
    entity_id: !input triggers
    to: "on"

action:
  # Choose action based on the sun's elevation
  - choose:
      # Sun is below the horizon
      - conditions:
          - condition: sun
            after: sunset
            after_offset: !input night_offset
            before: sunrise
            before_offset: !input day_offset
        sequence:
          # Activate night scene
          - service: scene.turn_on
            data:
              transition: !input cross_fade
            target:
              entity_id: !input night_scene
      # Sun is above the horizon
      - conditions:
          - condition: sun
            after: sunrise
            after_offset: !input day_offset
            before: sunset
            before_offset: !input night_offset
        sequence:
          # Activate day scene
          - service: scene.turn_on
            data:
              transition: !input cross_fade
            target:
              entity_id: !input day_scene
  # Await timeout once motion is no longer detected
  - wait_for_trigger:
      - platform: state
        entity_id: !input triggers
        to: "off"
        for:
          seconds: !input timeout
  # Activate off scene
  - service: scene.turn_on
    data:
      transition: !input cross_fade
    target:
      entity_id: !input off_scene

# Restart automation when trigger fires again
mode: restart
